.TH FONTDUMP 1 "September 25, 2005"
.SH NAME
fontdump \- extract fonts from files
.SH SYNOPSIS
.B fontdump \fR[\fBFILE\fR]
.SH DESCRIPTION
This manual page documents briefly the
.B fontdump
command.
.PP
\fBfontdump\fP can dump bitmap fonts of sizes 8x8, 8x14, and 8x16.
You can then use them later with the commands setfont or consolechars.
.SH SEE ALSO
.BR setfont (8).
